name: Deploy FastAPI Application image to Docker Hub

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code with checkout action
        uses: actions/checkout@v2
      
      - name: Set up Python with setup-python action
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'
      
      - name: Install the dependencies
        run: |
          python -m pip install --upgrade pip
          pip install fastapi[standard] uvicorn docker
  
  deploy: 
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build with command 
        run: |
          docker build -t swastiksharma/fastproject:latest fastproject/.
      
      - name: Push to Docker Hub
        run: |
          docker push swastiksharma/fastproject:latest